#!/bin/sh

if [ $# -lt 1 ]; then
    echo "usage: ./projets_idf [OPTION] (-s <filter>: sort by status, -m <filter>: sort by mode, -i: information)"
    exit -1
fi

statut_filter_on=0
mode_filter_on=0
if [ $1 == "-s" ]; then
    data=$(curl "https://data.iledefrance-mobilites.fr/explore/dataset/projets_lignes_idf/download/?format=json&timezone=Europe/Berlin&lang=fr")
    data_json=$(echo $data | jq -s -c '.[] | sort_by(.fields.statut, .fields.mode)');

    if [ $# -eq 2 ] && [[ "$2" =~ ^[0-9]$ ]]; then
        statut_filter_on=1
        statut_filter=$2
    fi
elif [ $1 == "-m" ]; then
    data=$(curl "https://data.iledefrance-mobilites.fr/explore/dataset/projets_lignes_idf/download/?format=json&timezone=Europe/Berlin&lang=fr")
    data_json=$(echo $data | jq -s -c '.[] | sort_by(.fields.mode)');

    if [ $# -eq 2 ] && [[ "$2" =~ ^[0-9]$ ]]; then
        mode_filter_on=1
        mode_filter=$2
    fi
elif [ $1 == "-i" ]; then
    echo "Statut de l'opération en cours (-s <statut_id>)"
    echo "1 = études préalables"
    echo "2 = DOCP"
    echo "3 = concertation préalable, débat public"
    echo "4 = schéma de principe"
    echo "5 = enquête publique"
    echo "6 = arrêté de DUP"
    echo "7 = phase AVP (conception générale)"
    echo "8 = phase PRO (conception détaillée)"
    echo "9 = phase travaux"
    echo "10 = mise en service"
    echo ""
    echo "Mode de transport, selon nouvelle charte des modes (-m <mode_id>)"
    echo "1 = metro"
    echo "2 = bus"
    echo "3 = tramway"
    echo "4 = rer"
    exit 0
else
    echo "usage: ./projets_idf [OPTION] (-s <filter>: sort by status, -m <filter>: sort by mode, -i: information)"
    exit -1
fi



function get_field
{
    printf "%-$3s" "$(echo $1 | jq -r ".fields.${2}")"
}



echo "   EDIT  | DUP | DATE_DUP |ETA|      NOM PROJET      |      NOM OPERATION"
for i in $(seq 1  $(echo $data_json | jq -r ". | length")); do

    fields=$(echo $data_json | jq -r ".[$((i - 1))]")

    statut=$(get_field "$fields" statut 1)
    mode=$(get_field "$fields" mode 1)
    if [ $statut_filter_on == 0 ] || [ $statut_filter_on == 1 -a $statut == $statut_filter ]; then

        if [ $mode_filter_on == 0 ] || [ $mode_filter_on == 1 -a $mode == $mode_filter ]; then

            printf "$(date -d $(get_field "$fields" date_editi 10) +"%d/%m/%y") | "

            dup=$(get_field "$fields" dup 1)
            if [ $dup == 1 ]; then
                printf "OUI | $(date -d $(get_field "$fields" dup_date 10) +"%d/%m/%y") | "
            else
                printf "NON |    __    | "
            fi

            printf "$statut | "
            printf "$(get_field "$fields" nom_projet 20) | "
            printf "$(get_field "$fields" operation 80)\n"
        fi
    fi
done
